### ISSUE TITLE
Constant NullPointerExceptions in location checking logic

### ISSUE THREAD

**Issue by robmonte** [Chris-Bitler/Runelite-StealingArtefacts#10] opened 2022-08-03 03:12 UTC
```
java.lang.NullPointerException: null
	at io.cbitler.stealingartefacts.StealingArtefactsPlugin.isInPisc(StealingArtefactsPlugin.java:322)
	at io.cbitler.stealingartefacts.StealingArtefactsPlugin.onGameTick(StealingArtefactsPlugin.java:153)
etc...
```

~For some reason WorldPoint is causing occasional bursts of many NullPointerExceptions like above.~
Upon further investigation, I am getting _constant_ NPE's from this bit of code. Not sure why WorldPoint would be causing this when I am standing in-game.

Located here: https://github.com/Chris-Bitler/Runelite-StealingArtefacts/blob/master/src/main/java/io/cbitler/stealingartefacts/StealingArtefactsPlugin.java#L322

**Comment by aturnerr** [comment] 2022-08-05 10:33
This is fixed in #9. Looking at your error this is caused by [#L153](https://github.com/Chris-Bitler/Runelite-StealingArtefacts/blob/master/src/main/java/io/cbitler/stealingartefacts/StealingArtefactsPlugin.java#L153).

**Closed as completed** 2022-08-17 19:14 UTC
